--- #YAML:1.0
name:               Chart-Plot-Tagged
version:            0.02
abstract:           Plot with tags
author:
    - Francois PERRAD (francois.perrad@gadz.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Chart::Plot:  0.11
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
